ARG BASEIMAGE
FROM $BASEIMAGE as compile
FROM openjdk:8-jre-slim
RUN mkdir -p /var/app
EXPOSE 8080
WORKDIR /var/app
COPY --from=compile /var/app/build/libs/backend21-1.0-SNAPSHOT.jar /var/app
RUN mkdir -p /var/app/docker
COPY --from=compile /var/app/docker/start.sh /var/app/docker/start.sh
CMD bash docker/start.sh